apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: my-k8s-app
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: vlunaski/k-client-2
      context: client
      docker:
        dockerfile: Dockerfile
    - image: vlunaski/k-query
      context: query
      docker:
        dockerfile: Dockerfile
    - image: vlunaski/k-moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
    - image: vlunaski/k-comment
      context: comments
      docker:
        dockerfile: Dockerfile
    - image: vlunaski/k-event
      context: event-bus
      docker:
        dockerfile: Dockerfile
    - image: vlunaski/k-post
      context: posts
      docker:
        dockerfile: Dockerfile

